# Flowspec Plugin Manifest
# Declares flowspec as a layered extension of github/spec-kit

name: flowspec
version: 0.0.20
type: layered-extension
author: jpoley
repository: https://github.com/jpoley/flowspec

# Base dependency
extends:
  name: spec-kit
  repository: github/spec-kit
  version: 0.0.20
  strategy: overlay

# What this plugin provides
provides:
  # Custom slash commands (flow:* namespace)
  commands:
    - path: templates/commands/flowspec/specify.md
      name: flow:specify
      description: Product Requirements Manager
    - path: templates/commands/flowspec/plan.md
      name: flow:plan
      description: Architecture & Platform Planning
    - path: templates/commands/flowspec/research.md
      name: flow:research
      description: Market Research & Analysis
    - path: templates/commands/flowspec/implement.md
      name: flow:implement
      description: Multi-Agent Implementation
    - path: templates/commands/flowspec/validate.md
      name: flow:validate
      description: QA, Security, Release Validation
    - path: templates/commands/flowspec/operate.md
      name: flow:operate
      description: SRE Operations

  # Language-specific expertise
  languages:
    - name: python
      path: .languages/python/
      features:
        - experts
        - agent-personas
        - resources
        - principles
    - name: go
      path: .languages/go/
      features:
        - experts
        - agent-personas
        - resources
        - principles
    - name: rust
      path: .languages/rust/
      features:
        - experts
        - agent-personas
        - resources
        - principles
    # Add other languages...

  # Extended templates (override base)
  templates:
    - source: templates/flowspec-plan-template.md
      destination: .specify/flowspec-plan-template.md
      merge_strategy: override

# Installation behavior
installation:
  # Two-stage download
  stages:
    - name: base
      source: github/spec-kit
      version: 0.0.20
      files: all
    
    - name: extension
      source: jpoley/flowspec
      version: 0.0.20
      files:
        - templates/commands/flowspec/**
        - .languages/**
        - memory/constitution.md
  
  # Merge rules when conflicts occur
  merge_rules:
    - pattern: "**/*.md"
      strategy: override
      description: "Extension templates override base"
    - pattern: ".claude/commands/**"
      strategy: merge
      description: "Combine commands from both sources"
    - pattern: ".specify/scripts/**"
      strategy: keep-both
      description: "Keep scripts from both, prefer extension on conflicts"

# Upgrade behavior
upgrade:
  sync_base: true
  description: "Pull latest spec-kit, then re-apply flowspec overlay"
