name: Bug Report
description: Report a bug or unexpected behavior in flowspec
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before Submitting

        - [ ] I have searched existing issues to ensure this bug has not been reported
        - [ ] I have checked the [documentation](https://github.com/jpoley/flowspec/tree/main/docs) for relevant information
        - [ ] I am using a supported version of flowspec

        Thank you for taking the time to report this issue! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What happened instead?
    validations:
      required: true

  - type: input
    id: flowspec-version
    attributes:
      label: flowspec Version
      description: Output of `specify --version` or `uv tool list | grep specify`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "3.11.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (RHEL/CentOS/Fedora)
        - Linux (Other)
        - Windows
        - Windows WSL
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output or error messages
      render: shell
      placeholder: |
        $ specify init
        Error: ...

  - type: checkboxes
    id: checklist
    attributes:
      label: Final Checklist
      options:
        - label: I have provided all requested information
          required: true
        - label: I can reproduce this issue consistently
          required: false
        - label: This issue affects my workflow significantly
          required: false
